version: '3.8'

services:
  db:
    image: postgres:16
    container_name: smart_url_db
    environment:
      POSTGRES_DB: smart_url
      POSTGRES_USER: jim
      POSTGRES_PASSWORD: jim
    ports:
      - "5432:5432"  # Map host port 5432 to container port 5432
